import os
from datetime import datetime
from news_fetcher import NewsFetcher
from summarizer import Summarizer

def main():
    print(f"--- AI News Automation Started at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ---")
    
    fetcher = NewsFetcher()
    summarizer = Summarizer()
    
    print("Fetching latest news articles...")
    articles = fetcher.fetch_latest_news(limit_per_feed=2)
    
    if not articles:
        print("No articles found.")
        return

    report_content = f"# AI Daily News Report - {datetime.now().strftime('%Y-%m-%d')}\n\n"
    report_content += "Generated by Antigravity Automation using Groq Llama 3.\n\n"
    report_content += "---\n\n"

    for i, article in enumerate(articles):
        print(f"Summarizing article {i+1}/{len(articles)}: {article['title']}")
        summary = summarizer.summarize(article['title'], article['summary'] or article['title'])
        
        report_content += f"## {article['title']}\n"
        report_content += f"**Source:** {article['source']} | **Date:** {article['published']}\n\n"
        report_content += f"{summary}\n\n"
        report_content += f"[Read more here]({article['link']})\n\n"
        report_content += "---\n\n"

    report_file = "news_report.md"
    with open(report_file, "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print(f"Report generated successfully: {os.path.abspath(report_file)}")

if __name__ == "__main__":
    main()
